"use client";

import { useParams, useSearchParams } from "next/navigation";
import { useReadContract } from "wagmi";
import {
  ARC_RECEIPTS_ADDRESS,
  ARC_RECEIPTS_ABI,
} from "../../../lib/arcReceiptsContract";

const categoryLabels: Record<number, string> = {
  0: "Salary",
  1: "Invoice",
  2: "Donation",
  3: "Subscription",
  4: "Test Purchase",
  5: "Loan repayment",
  6: "Other",
};

function formatUsdc(amount: bigint): string {
  const DECIMALS = BigInt("1000000");
  const whole = amount / DECIMALS;
  const frac = amount % DECIMALS;
  const fracStr = frac.toString().padStart(6, "0").replace(/0+$/, "");
  return fracStr ? `${whole.toString()}.${fracStr}` : whole.toString();
}

function formatTimestamp(ts: bigint): string {
  const ms = Number(ts) * 1000;
  const d = new Date(ms);
  return d.toLocaleString();
}

export default function ReceiptPage() {
  const params = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const id = params?.id;
  const receiptId = id ? BigInt(id) : BigInt(0);

  // 🔹 نحاول نقرأ tx من كويري سترنغ: /receipt/5?tx=0x123...
  const txHash = searchParams.get("tx") || null;

  const { data, isLoading, error } = useReadContract({
    address: ARC_RECEIPTS_ADDRESS,
    abi: ARC_RECEIPTS_ABI,
    functionName: "getReceipt",
    args: [receiptId],
    query: {
      enabled: !!id,
    },
  } as any);

  if (!id) {
    return (
      <section className="min-h-[50vh] flex items-center justify-center text-sm text-slate-400">
        No receipt id provided.
      </section>
    );
  }

  if (isLoading) {
    return (
      <section className="min-h-[50vh] flex items-center justify-center text-sm text-slate-400">
        Loading receipt #{id} from chain...
      </section>
    );
  }

  if (error) {
    return (
      <section className="min-h-[50vh] flex items-center justify-center">
        <div className="bg-red-950/40 border border-red-500/50 rounded-md px-4 py-3 text-sm text-red-200 max-w-md">
          Failed to load receipt #{id}: {error.message}
        </div>
      </section>
    );
  }

  if (!data) {
    return (
      <section className="min-h-[50vh] flex items-center justify-center text-sm text-slate-400">
        Receipt #{id} not found or empty.
      </section>
    );
  }

  const receipt = data as any;
  const receiptStruct = {
    id: receipt.id ?? receipt[0],
    from: receipt.from ?? receipt[1],
    to: receipt.to ?? receipt[2],
    amount: receipt.amount ?? receipt[3],
    category: Number(receipt.category ?? receipt[4]),
    reason: receipt.reason ?? receipt[5],
    sourceCurrency: receipt.sourceCurrency ?? receipt[6],
    destinationCurrency: receipt.destinationCurrency ?? receipt[7],
    corridor: receipt.corridor ?? receipt[8],
    timestamp: receipt.timestamp ?? receipt[9],
  };

  // 🔹 لو فيه txHash نستخدم رابط المعاملة، غير كذا نرجع لرابط العقد كـ fallback
  const explorerLink = txHash
    ? `https://testnet.arcscan.app/tx/${txHash}`
    : `https://testnet.arcscan.app/address/${ARC_RECEIPTS_ADDRESS}`;

  const explorerLabel = txHash ? "Transaction" : "Contract";

  return (
    <section className="space-y-6">
      <header>
        <h1 className="text-2xl font-semibold mb-1 text-slate-50">
          Receipt #{receiptStruct.id.toString()}
        </h1>
        <p className="text-sm text-slate-400">
          Onchain payment receipt generated by the PaymentWithReceipt
          contract.
        </p>
      </header>

      <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-3 shadow-sm">
        <div className="flex justify-between items-center">
          <h2 className="text-lg font-semibold text-slate-50">
            Payment details
          </h2>
          <span className="text-xs px-2 py-1 rounded-full bg-indigo-950/60 text-indigo-200 border border-indigo-500/40">
            {categoryLabels[receiptStruct.category] ??
              `Category #${receiptStruct.category}`}
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
          <div>
            <div className="text-slate-400 text-xs mb-1">From</div>
            <div className="break-all text-slate-100">
              {receiptStruct.from}
            </div>
          </div>
          <div>
            <div className="text-slate-400 text-xs mb-1">To</div>
            <div className="break-all text-slate-100">
              {receiptStruct.to}
            </div>
          </div>
          <div>
            <div className="text-slate-400 text-xs mb-1">Amount (USDC)</div>
            <div className="text-slate-50 font-medium">
              {formatUsdc(receiptStruct.amount)} USDC
            </div>
          </div>
          <div>
            <div className="text-slate-400 text-xs mb-1">Timestamp</div>
            <div className="text-slate-100">
              {formatTimestamp(receiptStruct.timestamp)}
            </div>
          </div>
        </div>

        <div className="border-t border-slate-800 pt-3 mt-2 text-sm space-y-2">
          <div>
            <div className="text-slate-400 text-xs mb-1">
              Note / description
            </div>
            <div className="text-slate-100">{receiptStruct.reason}</div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-sm">
            <div>
              <div className="text-slate-400 text-xs mb-1">
                Token type from
              </div>
              <div className="text-slate-100">
                {receiptStruct.sourceCurrency}
              </div>
            </div>
            <div>
              <div className="text-slate-400 text-xs mb-1">
                Token type to
              </div>
              <div className="text-slate-100">
                {receiptStruct.destinationCurrency}
              </div>
            </div>
            <div>
              <div className="text-slate-400 text-xs mb-1">Payment route</div>
              <div className="text-slate-100">{receiptStruct.corridor}</div>
            </div>
          </div>
        </div>

        <div className="border-t border-slate-800 pt-3 mt-3 flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs">
          <div className="text-slate-400">
            {explorerLabel}:{" "}
            <a
              href={explorerLink}
              target="_blank"
              rel="noreferrer"
              className="underline"
            >
              View on ArcScan
            </a>
          </div>

          <button
            type="button"
            onClick={() =>
              typeof window !== "undefined" &&
              navigator.clipboard.writeText(window.location.href)
            }
            className="px-3 py-1 rounded-md bg-slate-50 text-slate-950 hover:bg-slate-200"
          >
            Copy receipt link
          </button>
        </div>
      </div>
    </section>
  );
}
